// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/abhinav/git-pr/editor (interfaces: Editor)

package editortest

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Editor interface
type MockEditor struct {
	ctrl     *gomock.Controller
	recorder *_MockEditorRecorder
}

// Recorder for MockEditor (not exported)
type _MockEditorRecorder struct {
	mock *MockEditor
}

func NewMockEditor(ctrl *gomock.Controller) *MockEditor {
	mock := &MockEditor{ctrl: ctrl}
	mock.recorder = &_MockEditorRecorder{mock}
	return mock
}

func (_m *MockEditor) EXPECT() *_MockEditorRecorder {
	return _m.recorder
}

func (_m *MockEditor) EditString(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "EditString", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockEditorRecorder) EditString(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "EditString", arg0)
}
