#!/bin/bash -ex

# Fixes the import of vendored directories inside mocks

PACKAGE=$(go list .)
find . '(' -name .git -o -name vendor ')' -prune -o -name '*.go' \
    -exec grep -l "Automatically generated by MockGen" '{}' ';' \
    -exec sed -i '' -e "s|\"$PACKAGE/vendor/|\"|" '{}' ';'
